# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-26 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='app',
            unique_together=set([('name', 'project')]),
        ),
    ]
