# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-03 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
