# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_extlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extlog',
            name='object_instance',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='object values after the action'),
        ),
    ]
