# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-05 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_extlog', '0002_extlog_object_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extlog',
            name='object_instance',
        ),
    ]
