# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-10 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_signup_is_ready'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField(help_text="Use '|' for seperating paras", max_length=5000)),
                ('button', models.BooleanField(default=False)),
                ('button_name', models.CharField(blank=True, max_length=200, null=True)),
                ('button_path', models.CharField(blank=True, max_length=200, null=True)),
                ('user_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.UserAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
