# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-10 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
