# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-26 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modeller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_type', models.IntegerField(blank=True, choices=[(1, 'AutoField'), (2, 'IntegerField'), (3, 'FloatField'), (4, 'DateField'), (5, 'DateTimeField'), (6, 'EmailField'), (7, 'TimeField'), (8, 'DecimalField'), (9, 'CharField'), (10, 'SlugField'), (11, 'TextField'), (12, 'URLField'), (13, 'BigIntegerField'), (14, 'SmallIntegerField'), (15, 'PositiveSmallIntegerField'), (16, 'BooleanField'), (17, 'ForeignKey'), (18, 'ManyToManyField'), (19, 'OneToOneField'), (20, 'DurationField')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SerializerObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('field_parms', models.ManyToManyField(to='modeller.ModelField')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeller.ModelObject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customfield',
            name='serializer_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serializer.SerializerObject'),
        ),
    ]
