# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-26 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('serializer', '0001_initial'),
        ('modeller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=200)),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='app.App')),
                ('queryset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modeller.QuerySet')),
                ('serializer_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serializer.SerializerObject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quanta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100)),
                ('quanta_type', models.CharField(choices=[('DIC', 'Dictionary'), ('ARY', 'Array'), ('INT', 'Intiger'), ('STR', 'String'), ('DT', 'DateTime')], max_length=3)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='endpoint.Quanta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
