# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-26 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.SlugField()),
                ('description', models.TextField(max_length=1000, null=True)),
                ('data_base', models.IntegerField(blank=True, choices=[(1, 'sqlite3'), (2, 'postgresql_psycopg2')], null=True)),
                ('is_created', models.BooleanField(default=False)),
                ('host_url', models.CharField(max_length=200, null=True)),
                ('account', models.ManyToManyField(related_name='projects', to='account.UserAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
